name: sync-master

on:
  push:
    branches: [ ci-sync ]
  # schedule:
  #   - cron: '0 13 * * 2' # https://crontab.guru/#0_13_*_*_2 "At 13:00 on Tuesday."
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - run: hub --help
      - run: hub status
      - run: hub remote add upstream https://github.com/kaitai-io/kaitai_struct_formats.git
      - run: hub pull --rebase upstream master
      - run: hub push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
